title : Another Blog
tagline: More blog system testing
author :
  name : Jon Moore
  email : jonmoo@usefulgeek.com
  github : jonmoo
  twitter : thejonmoore

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
